# 复旦新闻物料库文本分类

In [1]:
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import numpy as np

## 预处理
引入语料库, 去除特殊符号, 并进行分词处理
选择3个分类, 每个分类15篇文档

### 载入语料库
这里的语料库格式不太统一, 所以加载不方便

In [2]:
r1 =  '[a-zA-Z0-9’\n·\s＊!"：#$%&\'()◆●（）＠②*+,-./:;<=>?@，。?★、…【】《》？——“”‘’！[\$$^_`{|}~]+'

dic = {4: 'C4-Literature', 5: 'C5-Education', 6: 'C6-Philosophy', 17: 'C17-Communication'}

y_train = []; y_test = []
corpus_train = [] ; corpus_test = []
num_classes = 3
num_doc = 32   # 最后一篇文档的编号
# num_testdoc = 3
       
# D:\CS\dataset\NLP\answer\C3-Art\C3-Art0002.txt
counter_testSet = 0
for i in range(10, num_doc+2, 2):
    with open('D:\\CS\\dataset\\NLP\\answer\\' + dic[4] + '\\' + dic[4] + str(i) + '.txt', 'r', encoding='utf-8') as f:
        counter_testSet += 1 
        text = f.read()
        text = re.sub(r1, '', text)
        corpus = ' '.join(jieba.cut(text))
        if counter_testSet < 10:
            y_train.append(4)
            corpus_train.append(corpus)
        else:
            y_test.append(4)
            corpus_test.append(corpus)
            
counter_testSet = 0
for i in range(10, num_doc+2, 2):
    with open('D:\\CS\\dataset\\NLP\\answer\\' + dic[5] + '\\' + dic[5] + '0'+ str(i) + '.txt', 'r', encoding='utf-8') as f:
        counter_testSet += 1
        text = f.read()
        text = re.sub(r1, '', text)
        corpus = ' '.join(jieba.cut(text))
        if counter_testSet < 10:
            y_train.append(5)
            corpus_train.append(corpus)
        else:
            y_test.append(5)
            corpus_test.append(corpus)
            
counter_testSet = 0
for i in range(10, num_doc+2, 2):
    with open('D:\\CS\\dataset\\NLP\\answer\\' + dic[6] + '\\' + dic[6] + str(i) + '.txt', 'r', encoding='utf-8') as f:
        counter_testSet += 1
        text = f.read()
        text = re.sub(r1, '', text)
        corpus = ' '.join(jieba.cut(text))
        if counter_testSet < 9:
            y_train.append(6)
            corpus_train.append(corpus)
        else:
            y_test.append(6)
            corpus_test.append(corpus)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\levovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.458 seconds.
Prefix dict has been built succesfully.


In [3]:
corpus_test[1]

'日期 版号 标题 为雅 文化 升温 添柴 东方出版社 重版 一批 现代 学术 名著 作者 祝华新 正文 本报记者 祝华新 新年伊始 郭沫若 十 批判 书 等 一批 民国时期 的 著名 学术著作 带 着 一缕 淡淡的 墨香以 简体 横排 的 新 版本 走 下 印刷机 这 就是 东方出版社 献给 莘莘学子 的 新年礼物 民国 学术 经典 文库 解放后 一些 出版社 曾经 重印 或 影印 过 民国时期 部分 学术著作 但 较为 零碎 未 成 系统 而且 旧版 的 繁体 竖排 给 当代 中青年 读者 带来 诸多不便 该 文库 从 民国时期 总书 目的 十余万 种 中文 图书 中 精选 出 ３ １ 种 著作 展示 了 民国时期 在 思想史 历史 文学史 等 方面 的 重要 学术 成果 学术 再 上层 楼 的 阶梯 东西 文化 大规模 碰撞 导致 的 中国 传统 学术 向 现代 学术 的 演变 自 晚清 开始 辛亥革命 后 才 取得 长足 的 进展 二三十 年代 的 学界 可谓 杂花生树 群莺 乱飞 百舸争流 正如 著名 学者 张岱年 在 总序 中所言 当时 许多 学者 继承 了 清代 朴学 的 作风 考据 比较 精审 ； 也 有些 学者 对于 宋明理学 有 较 多 的 了解 对于 深邃 的 义理 有 较 深 的 体会 ； 同时 许多 学者 都 在 一定 程度 上 参考 了 西方 的 治学 方法 致力于 中西 学术 的 会通 与 融合 因而 达到 了 学术研究 的 较 高水平 收入 文库 的 作者 中 有些 是 今人 非常 熟悉 的 如 梁启超 蔡元培 鲁迅 陈寅恪 陶行知 阿英 郑振铎 等 但 熟悉 中 又 有点 陌生 比如 很多 人 知道 蔡和森 的 名字 但 未必 了解 这位 中共 早期 理论家 还 著 有 一本 社会 进化史 在 严复 鼓吹 的 达尔文主义 基础 上 初步 引入 马克思主义 的 历史观 而 有些 作者 连 相关 专业 的 研究生 都 没听说过 有些 著作 即使 在 北京 图书馆 也 查不到 比如 晚明 思想 史论 的 作者 嵇文甫 解放后 曾 出任 河南省 副省长 后来 又 主动 辞职 到 郑州大学 当 一名 教书匠 可叹 这 段 学苑 佳话 早已 湮没 在 岁月 的 深处 这 批学 人大 都 有 国学 的 扎实 根基 又 周游列国 饱经 欧风美雨 的

In [4]:
print('corpus train length: ', len(corpus_train))
print('corpus test length : ', len(corpus_test))

corpus train length:  26
corpus test length :  10


### 导入停用词

In [5]:
#从文件导入停用词表
stpwrdpath = r"D:\Repositories\Datasets\NLP\chineseStopWords.txt"
stpwrd_dic = open(stpwrdpath, 'r', encoding='UTF-8-sig')
# stpwrd_dic = open('new2.txt',  'r', encoding='UTF-8-sig'
stpwrd_content = stpwrd_dic.read()
#将停用词表转换为list  
stpwrdlst = stpwrd_content.splitlines()
stpwrd_dic.close()

In [6]:
print(stpwrdlst)

['啊', '阿', '哎', '一个', '一举', '一体', '一册', '一动', '一出', '一只', '一员', '一大', '一套', '一对', '一派', '一层', '一副', '一座', '一把', '一本', '一束', '一步', '一段', ' 一段时间', ' 一派', ' 一点', ' 一碧', ' 一种', ' 一窥', ' 一章', ' 一类', ' 一系列', ' 一级', ' 一经', ' 一股', ' 一节', ' 一著', ' 一词', ' 一道', ' 一部', ' 一部分', ' 一门', ' 一阵阵', ' 一面镜子', ' 一项', ' 一须', ' 一颗', '三十', '三大', '三层', '三年', '三性', '哎呀', '哎哟', '唉', '俺', '俺们', '按', '按照', '吧', '吧哒', '把', '罢了', '被', '本', '广阔', '本着', '开拓', '拓展', '开拓', '比', '比方', '比如', '鄙人', '彼', '彼此', '边', '别', '别的', '别说', '并', '并且', '三个', '不比', '不成', '不单', '不但', '不独', '不管', '不光', '不过', '不仅', '不拘', '不论', '不怕', '不然', '不如', '不特', '不惟', '不问', '不只', '朝', '朝着', '趁', '趁着', '乘', '冲', '除', '除此之外', '除非', '除了', '此', '此间', '此外', '从', '从而', '出', '打', '待', '但', '但是', '当', '当着', '到', '得', '的', '的话', '等', '等等', '地', '第', '叮咚', '对', '对于', '多', '多少', '而', '而况', '而且', '而是', '而外', '而言', '而已', '尔后', '反过来', '反过来说', '反之', '非但', '非徒', '否则', '嘎', '嘎登', '刚', '刚刚', '该', '赶', '个', '各', '各个', '各位', '各种', '各自', '给', '根据', '跟', '故', '故此', '固然', 

### TF-IDF

In [7]:
tfidf = TfidfVectorizer(stop_words=stpwrdlst)
merged_corpus = corpus_train.copy()
merged_corpus.extend(corpus_test)   # 注意extend方法返回值为None

re = tfidf.fit_transform(merged_corpus)     # 这里要同时考虑训练集和测试集语料

D:\study\Anaconda\lib\site-packages\sklearn\feature_extraction\text.py:286: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['一段时间', '一点', '一碧', '一种', '一窥', '一章', '一类', '一系列', '一级', '一经', '一股', '一节', '一著', '一词', '一道', '一部', '一部分', '一门', '一阵阵', '一面镜子', '一项', '一须', '一颗'] not in stop_words.
  sorted(inconsistent))


In [8]:
print(re) 

  (0, 3481)	0.009070169663414574
  (0, 4213)	0.009070169663414574
  (0, 3768)	0.00791438798991609
  (0, 4855)	0.017307278646298857
  (0, 1479)	0.03996306907421868
  (0, 685)	0.01998153453710934
  (0, 712)	0.11995889523250142
  (0, 3336)	0.1879108088676009
  (0, 329)	0.07669968204547602
  (0, 2240)	0.7637350550307946
  (0, 255)	0.045008631574022545
  (0, 3364)	0.049778003179174836
  (0, 1828)	0.036194488736871915
  (0, 2199)	0.03796070182413454
  (0, 4505)	0.06751294736103382
  (0, 4862)	0.05266870670264048
  (0, 782)	0.009324354673651458
  (0, 6084)	0.029374425193492103
  (0, 3843)	0.009070169663414574
  (0, 325)	0.029374425193492103
  (0, 4495)	0.022504315787011273
  (0, 2202)	0.029374425193492103
  (0, 3969)	0.02633435335132024
  (0, 4151)	0.029374425193492103
  (0, 3725)	0.016592667726391612
  :	:
  (35, 2695)	0.02609801492666638
  (35, 280)	0.02609801492666638
  (35, 4934)	0.02609801492666638
  (35, 1215)	0.02609801492666638
  (35, 5821)	0.02609801492666638
  (35, 4291)	0.026098014

### 然后抽取每篇文档的前N个tfidf, 给每篇文档组成词向量进行分类

In [9]:
idf_mat = re.toarray()
print(idf_mat)
print(idf_mat.shape)    # 训练集测试集一共36篇文档, 所有文档包含的不重复词个数为6139

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(36, 6139)


In [10]:
ID_list = []
topN = 20   # 每篇文档提取前topN个tf-idf值对应的词的ID

for row in idf_mat: 
    ID_list.extend(np.argsort(-row)[:topN])

ID_list = list(set(ID_list))
print(ID_list)

[4102, 4108, 2064, 2065, 2072, 4122, 4126, 4133, 46, 2110, 2111, 68, 4185, 90, 4186, 4196, 4197, 102, 2151, 4200, 4205, 4206, 2159, 2158, 2161, 2163, 4223, 129, 4232, 2185, 4233, 2189, 4238, 2191, 2192, 2195, 4244, 2197, 2199, 2206, 2208, 2209, 4257, 4260, 2216, 2224, 2237, 2240, 4289, 4295, 4296, 2252, 4303, 2263, 2264, 222, 4319, 4321, 227, 4326, 230, 2279, 231, 2283, 2286, 4335, 2288, 241, 2290, 4339, 4340, 2294, 2295, 250, 4346, 256, 2306, 2307, 261, 4357, 2313, 2315, 2318, 4367, 4366, 274, 4374, 4390, 4395, 305, 2357, 2358, 4407, 4416, 323, 329, 330, 2379, 4435, 342, 4440, 344, 2395, 349, 2398, 4454, 4472, 4474, 4481, 2434, 387, 4484, 2441, 4494, 2448, 2450, 4498, 406, 4505, 411, 4515, 425, 2479, 4529, 4530, 2483, 2488, 4538, 2491, 4549, 466, 4563, 2516, 2517, 4565, 468, 2525, 4575, 2528, 479, 482, 4579, 486, 2535, 2534, 4583, 4588, 4590, 4591, 4593, 498, 2545, 508, 2556, 2557, 2559, 517, 2566, 524, 531, 2584, 543, 4641, 547, 4643, 559, 560, 2612, 2626, 2627, 582, 2631, 2632, 2630

也许可以考虑用idf的分位数分别为每篇文档选取topN个词ID

In [11]:
print('features per doc: ',len(ID_list))

features per doc:  533


上面数组每一个元素代表某个词的ID, 经过去重后, topN=30意味着每个文档有794个特征

### 构建文档的词向量矩阵

In [12]:
trainSet = []; testSet = []
for doc in range(0, len(corpus_train) + len(corpus_test)):
    temp_list = []
    for ID in ID_list:
        temp_list.append(idf_mat[doc][ID])
    if doc < len(corpus_train):
        trainSet.append(temp_list)
    else:
        testSet.append(temp_list)

trainSet, testSet = np.array(trainSet), np.array(testSet)

## Modeling

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='auto', solver='saga')
model.fit(trainSet, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='saga',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(testSet)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_pred, y_test))

              precision    recall  f1-score   support

           4       1.00      0.67      0.80         3
           5       0.60      1.00      0.75         3
           6       1.00      0.75      0.86         4

   micro avg       0.80      0.80      0.80        10
   macro avg       0.87      0.81      0.80        10
weighted avg       0.88      0.80      0.81        10

[[2 0 0]
 [1 3 1]
 [0 0 3]]


In [15]:
from sklearn.model_selection import cross_val_score

tempSet = trainSet.copy()
tempSet = np.concatenate((tempSet, testSet), axis=0)
templabel = y_train.copy()
templabel.extend(y_test)

print('cross validation score:')
cross_val_score(model, X=tempSet, y=templabel, cv=5, scoring='accuracy').mean()

cross validation score:


0.9222222222222222

In [16]:
from sklearn.naive_bayes import *

clf_NB_multinomial = MultinomialNB()
cross_val_score(clf_NB_multinomial, tempSet, templabel, cv=5, scoring='accuracy').mean()

0.9

In [17]:
clf_NB_gaussian = GaussianNB()
cross_val_score(clf_NB_gaussian, tempSet, templabel, cv=5, scoring='accuracy').mean()

0.6555555555555557

为什么 两个NB性能相差这么多? 有必要深究一下